# Generated by Django 6.0 on 2026-09-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('student_id', models.CharField(blank=True, default='', max_length=30)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('year_of_study', models.CharField(blank=True, default='', max_length=20)),
                ('favorite_book', models.CharField(blank=True, default='', max_length=200)),
                ('motivation', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
