# Generated by Django 6.0 on 2026-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membershipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
