# Generated by Django 6.0 on 2026-09-10 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membershipapplication_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='policy_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
