# Generated by Django 6.0 on 2026-09-10 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membershipapplication_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='officer_title',
            field=models.CharField(choices=[('PRESIDENT', 'Club President'), ('VICE_PRESIDENT', 'Vice President'), ('SOCIAL_MEDIA_LEAD', 'Social Media Lead'), ('RESEARCH_LEAD', 'Research & Editorial Lead'), ('EVENT_LEAD', 'Event Organizing Lead'), ('FINANCE_LEAD', 'Finance Lead'), ('NONE', 'General Member')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Club President (Owner)'), ('OFFICER', 'Executive Officer'), ('MEMBER', 'Club Member'), ('ADMIN', 'Club Executive / Admin'), ('GUEST', 'Guest / Visitor')], default='MEMBER', max_length=20),
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('record_type', models.CharField(choices=[('CONTRIBUTION', 'Member Contribution / Dues'), ('SPONSORSHIP', 'Corporate / University Sponsorship'), ('DONATION', 'Patron / Alumni Donation'), ('EXPENSE', 'Book Acquisition & Event Expense')], default='CONTRIBUTION', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('contributor_name', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_logged', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
