# Generated by Django 6.0 on 2026-10-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_managers_user_department_user_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
    ]
