# Generated by Django 6.0 on 2026-09-07 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='storysubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='storyprompt',
            name='prompt_text',
        ),
        migrations.AddField(
            model_name='storyprompt',
            name='prompt_type',
            field=models.CharField(choices=[('ORIGINAL_HOOK', 'Original Hook'), ('ALTERNATE_ENDING', 'Alternate Ending')], default='ORIGINAL_HOOK', max_length=30),
        ),
        migrations.AddField(
            model_name='storyprompt',
            name='story_opening',
            field=models.TextField(default='', help_text='1–2 paragraph premise/cliffhanger provided to members.'),
        ),
        migrations.AddField(
            model_name='storyprompt',
            name='title',
            field=models.CharField(default='Weekly Story Challenge', max_length=200),
        ),
        migrations.AlterField(
            model_name='storysubmission',
            name='content',
            field=models.TextField(help_text="Member's creative conclusion (30-350 words)"),
        ),
        migrations.AlterUniqueTogether(
            name='storysubmission',
            unique_together={('prompt', 'user')},
        ),
    ]
