# Generated by Django 6.0 on 2026-09-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_submitted_at_storysubmission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyprompt',
            name='story_opening',
            field=models.TextField(default='', help_text='The 1-2 paragraph premise or cliffhanger'),
        ),
    ]
