# Generated by Django 6.0 on 2026-09-13 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_discussionreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproposal',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='activities.bookproposal'),
        ),
    ]
