# Generated by Django 6.0 on 2026-09-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_bookproposal_likes_contentreport_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreport',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='activities.discussionreply'),
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_replies', to='activities.discussionreply'),
        ),
    ]
