# Generated by Django 6.0 on 2026-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('total_pages', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('pdf_file', models.FileField(help_text='PDF reading binary stream', upload_to='books/pdfs/')),
                ('guide_pdf', models.FileField(blank=True, help_text='Official discussion guide worksheet', null=True, upload_to='books/guides/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
