# Generated by Django 6.0 on 2026-09-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='guide_pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='guide_file',
            field=models.FileField(blank=True, help_text='Official discussion guide worksheet', null=True, upload_to='book_guides/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF reading binary stream', null=True, upload_to='books_pdf/'),
        ),
    ]
