# Generated by Django 6.0 on 2026-10-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_guide_pdf_book_guide_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_size',
            field=models.BigIntegerField(blank=True, default=0, help_text='Uploaded PDF file size in bytes', null=True),
        ),
    ]
