# Generated by Django 6.0 on 2026-09-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='passcode_hash',
            field=models.CharField(blank=True, default='', help_text='Hashed passcode for secure check-in verification', max_length=255),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='passcode',
            field=models.CharField(blank=True, default='', help_text='Raw 4-digit passcode (kept for admin desk display only)', max_length=255),
        ),
    ]
