# Generated by Django 6.0 on 2026-10-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_meeting_passcode_hash_alter_meeting_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='passcode_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when passcode was generated', null=True),
        ),
        migrations.AddField(
            model_name='readingcycle',
            name='meeting_title',
            field=models.CharField(blank=True, default='', help_text='Optional gathering label e.g. Saturday Review', max_length=255),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Passcode expiration timestamp (4-hour limit)', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_datetime',
            field=models.DateTimeField(help_text='Meeting start time'),
        ),
    ]
